apiVersion: v1
kind: Service
metadata:
  name: notbad-task
spec:
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: 5080
  selector:
    app: notbad-task
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notbad-task
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: notbad-task
  template:
    metadata:
      labels:
        app: notbad-task
    spec:
      containers:
        - name: notbad-task
          image: CONTAINER_IMAGE
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

